### PR TITLE
BaraaNazar/issue1

### LINKED ISSUE #1: Create the navbar and the router
about: Create the navbar and the router
labels: Enhancement
Summary
This will make the navbar on all pages of the project and also it must have a router

Screenshots
If applicable, add screenshots to help explain the feature.

Constraints / Details
What are the constraints for this feature? If there are any more details add them below.

### PR DESCRIPTION
**Pull request by BaraaNazar**
Fixes #1

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related Issue

Fixes # (issue)
If suggesting a new feature or change, please discuss it in an issue first

## Screenshots

(prefer animated gif)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally
- [x] Added tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I've run linter, prettier, and removed all `console.log`
- [x] I've reverted all the files back that are not related to the issue (App.js, index.js, ...)

### CODE REVIEW

**Review by Banel-Mikhael — APPROVED** [review]
LGTM

**Comment by Nma-sh98** [comment]
great!

**Review by Banel-Mikhael — APPROVED** [review]
LGTM

**Review by HeyamMasri — COMMENTED** [review]
great

**Review by Nma-sh98 — APPROVED** [review]
great!

**Review by HeyamMasri — COMMENTED** [review]
great

**Pull request merged**
